name: Java CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    VALIDATE_ALL_CODEBASE: true
    VALIDATE_JAVA: true
    VALIDATE_PYTHON: false
    VALIDATE_JAVASCRIPT: false
    VALIDATE_TYPESCRIPT: false
    VALIDATE_GO: false
    VALIDATE_YAML: false
    VALIDATE_MARKDOWN: false
    VALIDATE_DOCKERFILE: false
    VALIDATE_JSON: false
    VALIDATE_XML: false
    VALIDATE_BASH: false
    JAVA_FILE_NAME: checkstyle.xml
  - name: Test with Maven
    run: mvn --batch-mode --update-snapshots package